export default liste = [
  {
    id: 1,
    refrence: 1,
    title: 'Vaisselle post-réunion',
    address: 'Bepanda',
    complement: 'Carrefour 3 bordelles',
    date: '13/02/2020',
    description: "Hey, feel free to edit this paragraph by double click, or change style property on right side panel. Enjoy ;) Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    prix: 1000,
    image: 'https://previews.123rf.com/images/eljanstock/eljanstock1808/eljanstock180802522/106869261-women-icon-vector-isolated-on-white-background-women-transparent-sign.jpg',
    employer: 'Nigga',
    color:'#FFA500',
    fav: false
  },
  {
    id: 2,
    refrence: 2,
    title: 'Lessive',
    address: 'Bonanjo',
    complement: 'base navale',
    date: '13/02/2020',
    description: "Hey, feel free to edit this paragraph by double click, or change style property on right side panel. Enjoy ;) Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    prix: 800,
    image: 'https://previews.123rf.com/images/eljanstock/eljanstock1808/eljanstock180802522/106869261-women-icon-vector-isolated-on-white-background-women-transparent-sign.jpg',
    employer: 'Bruuuh',
    color:'#32CD32',
    fav: true
  },
  {
    id: 3,
    refrence: 3,
    title: 'Courses',
    address: 'Bonamoussadi',
    complement: 'Toiture verte',
    date: '13/02/2020',
    description: "Hey, feel free to edit this paragraph by double click, or change style property on right side panel. Enjoy ;) Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    prix: 1500,
    image: 'https://previews.123rf.com/images/eljanstock/eljanstock1808/eljanstock180802522/106869261-women-icon-vector-isolated-on-white-background-women-transparent-sign.jpg',
    employer: 'Zango La Dozo',
    color:'#FFA500',
    fav: true
  },
  {
    id: 4,
    refrence: 4,
    title: 'Démenagement',
    address: 'Makepe',
    complement: 'Rond point petit pays',
    date: '13/02/2020',
    description: "Hey, feel free to edit this paragraph by double click, or change style property on right side panel. Enjoy ;) Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    prix: 1400,
    image: 'https://previews.123rf.com/images/eljanstock/eljanstock1808/eljanstock180802522/106869261-women-icon-vector-isolated-on-white-background-women-transparent-sign.jpg',
    employer: 'Nyangono',
    color:'#32CD32',
    fav: true
  },
  {
    id: 5,
    refrence: 5,
    title: 'Nettoyage',
    address: 'Kotto',
    complement: 'bloc',
    date: '13/02/2020',
    description: "Hey, feel free to edit this paragraph by double click, or change style property on right side panel. Enjoy ;) Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    prix: 600,
    image: 'https://previews.123rf.com/images/eljanstock/eljanstock1808/eljanstock180802522/106869261-women-icon-vector-isolated-on-white-background-women-transparent-sign.jpg',
    employer: 'Grand Barrack',
    color:'#FFA500',
    fav: false
  },
  {
    id: 6,
    refrence: 6,
    title: 'Aucune idée',
    address: 'New-Bell',
    complement: 'Sacred Heart',
    date: '13/02/2020',
    description: "Hey, feel free to edit this paragraph by double click, or change style property on right side panel. Enjoy ;) Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    prix: 400,
    image: 'https://previews.123rf.com/images/eljanstock/eljanstock1808/eljanstock180802522/106869261-women-icon-vector-isolated-on-white-background-women-transparent-sign.jpg',
    employer: 'Dunno',
    color:'#32CD32',
    fav: false
  }
]